### ISSUE TITLE
When I am logged in and open main page I got error.

### ISSUE THREAD

**Issue by thecodeholic** [omcrn/secret-santa-firebase#10]
![image](https://cloud.githubusercontent.com/assets/4627922/21522907/f9ff00ce-cd22-11e6-91c0-23229da7a3a9.png)

**Comment by guga-grigolia** [comment]
cannot reproduce. please link jsbin.

**Comment by thecodeholic** [comment]
Please check this main url [https://secretsanta-7b0cc.firebaseapp.com/#/](url)
